/**
 * Cross-engine parity, run INSIDE workerd.
 *
 * engine/tests/parity.test.ts already compares the TypeScript engine to the
 * Python reference -- in Node. This file makes the same comparison in the
 * runtime that actually serves the site.
 *
 * The distinction is not academic. `activeResolver()` picks Temporal when the
 * global exists and Intl otherwise, and that global's presence differs between
 * local workerd and the deployed fleet. Without this file, an engine suite
 * green in Node would happily coexist with every contest an hour out in
 * production, and nothing would say so.
 *
 * The Python side is generated by tests/global-setup.ts (Node has child
 * processes; workerd does not) and imported here as a fixture.
 */

import { describe, expect, it } from "vitest";

import { expandYear, type Contest } from "../../engine/src/recurrence.js";
import { intlResolver, activeResolver } from "../../engine/src/zones.js";
import { CATALOG } from "../src/catalog.js";
import {
  PINNED_RESOLVER,
  resolverSelfCheck,
  runtimeReport,
} from "../src/runtime.js";
import fixture from "./fixtures/python-occurrences.json";

const YEARS = [2026, 2027, 2030, 2032];
const byYear = fixture as unknown as Record<string, Record<string, unknown>[]>;

describe("the resolver workerd is actually using", () => {
  it("is the pinned Intl resolver, not whatever the runtime would have chosen", () => {
    // Identity, not behaviour: a passing behavioural check would still pass if
    // Temporal happened to agree today and drifted tomorrow.
    expect(activeResolver()).toBe(intlResolver);
    expect(PINNED_RESOLVER).toBe("intl");
  });

  it("resolves every known DST edge to the instant Python computes", () => {
    const check = resolverSelfCheck();
    expect(check.failures, JSON.stringify(check.failures, null, 2)).toEqual([]);
    expect(check.pass).toBe(true);
  });

  it("records what it would have picked without the pin", () => {
    const report = runtimeReport();
    // Not an assertion about which -- that legitimately differs between local
    // workerd and the fleet, and the whole point of the pin is that it stops
    // mattering. What must hold is that the report tells the truth about it.
    expect(["intl", "temporal"]).toContain(report.wouldSelectWithoutPin);
    expect(report.resolver).toBe("intl");
    expect(report.pinned).toBe(true);
    expect(report.intlAvailable).toBe(true);
    if (report.wouldSelectWithoutPin !== report.resolver) {
      // Logged rather than failed: this is the exact condition the pin exists
      // for, so seeing it is confirmation, not breakage.
      console.warn(
        `[parity] this runtime would have selected ${report.wouldSelectWithoutPin} ` +
          "without the pin -- the pin is load-bearing here",
      );
    }
  });
});

describe("cross-engine parity inside workerd", () => {
  it("has a fixture for every parity year", () => {
    for (const year of YEARS) {
      expect(byYear[String(year)], `no Python dump for ${year}`).toBeInstanceOf(
        Array,
      );
      expect(byYear[String(year)].length).toBeGreaterThan(0);
    }
  });

  it.each(YEARS)(
    "every field of every occurrence matches Python for %i",
    (year) => {
      const fromPython = byYear[String(year)];
      const fromWorkerd = expandYear(CATALOG as Contest[], year).map((o) =>
        o.toDict(),
      );

      // Count first: zipping mismatched arrays produces a diff nobody can read,
      // and the count is the headline fact anyway.
      expect(
        fromWorkerd.length,
        `occurrence count differs for ${year}`,
      ).toBe(fromPython.length);

      for (let i = 0; i < fromWorkerd.length; i++) {
        expect(
          fromWorkerd[i],
          `${year} occurrence ${i} (${fromWorkerd[i].contest_id}) differs ` +
            "between workerd and the Python reference",
        ).toEqual(fromPython[i]);
      }
    },
  );

  it("puts no occurrence off by a whole hour", () => {
    // A targeted check for the specific failure the pin prevents. A generic
    // deep-equal failure says "these differ"; this says "these differ by
    // exactly an hour", which names the cause on the first read of the log.
    const year = 2026;
    const fromPython = byYear[String(year)];
    const fromWorkerd = expandYear(CATALOG as Contest[], year).map((o) =>
      o.toDict(),
    );

    const hourOff: string[] = [];
    for (let i = 0; i < Math.min(fromWorkerd.length, fromPython.length); i++) {
      const a = fromWorkerd[i].start as string | null;
      const b = fromPython[i].start as string | null;
      if (!a || !b || a === b) continue;
      const delta = Math.abs(Date.parse(a) - Date.parse(b));
      if (delta === 3_600_000) {
        hourOff.push(`${fromWorkerd[i].contest_id}: ${a} vs ${b}`);
      }
    }
    expect(
      hourOff,
      "occurrences are off by exactly one hour -- this is a timezone resolver " +
        "divergence inside workerd, not a rule bug:\n" +
        hourOff.join("\n"),
    ).toEqual([]);
  });
});
