/// <reference types="@cloudflare/vitest-pool-workers/types" />

/**
 * The Python side of the parity comparison.
 *
 * Generated by tests/global-setup.ts on every run and gitignored, so the file
 * is absent when `tsc` runs on a clean checkout. Declared here rather than
 * committed so that a stale fixture can never be what parity passes against.
 *
 * Typed loosely on purpose: this is the *other* engine's output, and the test's
 * whole job is to discover that its shape differs from ours.
 */
declare module "*python-occurrences.json" {
  const dump: Record<string, Record<string, unknown>[]>;
  export default dump;
}
